
println("        !!!!!!!!!!!!!");
println("       !!!!!!!!!!!!!!!!!");
println("     !!!!!!!!!!!!!!!!!!!!! ");
println("    !!!!!!!!!!!!!!!!!!!!!!!");
println("       !!!!!!!!!!!!!!!");
println("               ^");
println("              / \\");
println("             /   \\");
println("           _________");
print("             ^");
println(" ^");
println("            (- -)");
println("             ( )/ ");
println("              )");
println("           (((|)))");
print("       (((|)))");
println(" (((|)))");
println("     ______________________");
print("   __________________________");
